### ISSUE TITLE
Make the nais-cli handle Fasit applicationProperties containing comments

### ISSUE THREAD

**Issue by greger-nl** [nais/naisd#103]
The env operation of the nais-cli crashes if there is a Fasit alias for a resources of the type applicationProperties, and that property file contains one or more comments.

Crash output:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nais/naisd/api.FasitClient.mapToNaisResource(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0x54cbb, 0xc4205dc040, 0x17, 0xc4205dc020, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:557 +0x65f
github.com/nais/naisd/api.FasitClient.getScopedResource(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0xc420156380, 0x17, 0xc4201563e0, 0x15, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:387 +0x43d
github.com/nais/naisd/api.FasitClient.GetScopedResources(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0xc42032aa00, 0x13, 0x20, 0x7ffe27700ecb, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:162 +0x1d9
github.com/nais/naisd/api.(*FasitClient).GetScopedResources(0xc4203cac90, 0xc42032aa00, 0x13, 0x20, 0x7ffe27700ecb, 0x2, 0x7ffe27700ebb, 0xc, 0x7ffe27700eb3, 0x3, ...)
	<autogenerated>:1 +0xdd
github.com/nais/naisd/api.FetchFasitResources(0x170a7c0, 0xc4203cac90, 0x7ffe27700ebb, 0xc, 0x7ffe27700ecb, 0x2, 0x7ffe27700eb3, 0x3, 0xc42031d500, 0x12, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:282 +0x3f8
github.com/nais/naisd/cli/cmd.glob..func2(0x1753880, 0xc420093770, 0x1, 0x5)
	/go/src/github.com/nais/naisd/cli/cmd/environment.go:128 +0xa92
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).execute(0x1753880, 0xc420093720, 0x5, 0x5, 0x1753880, 0xc420093720)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1753ae0, 0x18, 0xc42027df70, 0x406094)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1753ae0, 0xc4203ca150, 0x105c5a5)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/go/src/github.com/nais/naisd/cli/nais.go:11 +0x31
```

If one tries to deploy the application through the nais deploy in jira one will only get a Bad gateway response:

```
2018-04-10 15:51:18,644 - REALLY_NAIS_DEPLOY - INFO - Calling deploy service...
2018-04-10 15:51:18,941 - REALLY_NAIS_DEPLOY - ERROR - HTTP Error 502: Bad Gateway
2018-04-10 15:51:18,943 - REALLY_NAIS_DEPLOY - ERROR - Bad Gateway
```

### Reproduce the issue
Nais-cli version: 234.0.0

The issue can be reproduced by using the nais.yaml file for saksoversikt:9.11, running the command `nais env` against the environments t and q. In the t environment the comment have been removed, but the comment is still present in the q environment.

#### Environment t - Working

This now works after the comment was removed from saksoversikt.properties in the t environment:
```
nais -z sbs env saksoversikt -e t5
Enter password for <user name>: 
...

```

#### Environment q - Does not work
Does not work, because the comment is still present i saksoversikt.properties in the q environment.

```
nais -z sbs env saksoversikt -e q5                                                              
Enter password for <user name>: 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nais/naisd/api.FasitClient.mapToNaisResource(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0x54cbb, 0xc4205dc040, 0x17, 0xc4205dc020, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:557 +0x65f
github.com/nais/naisd/api.FasitClient.getScopedResource(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0xc420156380, 0x17, 0xc4201563e0, 0x15, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:387 +0x43d
github.com/nais/naisd/api.FasitClient.GetScopedResources(0x10662b3, 0x15, 0xc42008c060, 0x7, 0xc42038a370, 0xa, 0xc42032aa00, 0x13, 0x20, 0x7ffe27700ecb, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:162 +0x1d9
github.com/nais/naisd/api.(*FasitClient).GetScopedResources(0xc4203cac90, 0xc42032aa00, 0x13, 0x20, 0x7ffe27700ecb, 0x2, 0x7ffe27700ebb, 0xc, 0x7ffe27700eb3, 0x3, ...)
	<autogenerated>:1 +0xdd
github.com/nais/naisd/api.FetchFasitResources(0x170a7c0, 0xc4203cac90, 0x7ffe27700ebb, 0xc, 0x7ffe27700ecb, 0x2, 0x7ffe27700eb3, 0x3, 0xc42031d500, 0x12, ...)
	/go/src/github.com/nais/naisd/api/fasit.go:282 +0x3f8
github.com/nais/naisd/cli/cmd.glob..func2(0x1753880, 0xc420093770, 0x1, 0x5)
	/go/src/github.com/nais/naisd/cli/cmd/environment.go:128 +0xa92
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).execute(0x1753880, 0xc420093720, 0x5, 0x5, 0x1753880, 0xc420093720)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1753ae0, 0x18, 0xc42027df70, 0x406094)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/nais/naisd/vendor/github.com/spf13/cobra.(*Command).Execute(0x1753ae0, 0xc4203ca150, 0x105c5a5)
	/go/src/github.com/nais/naisd/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/go/src/github.com/nais/naisd/cli/nais.go:11 +0x31
```

**Comment by greger-nl** [comment]
Snippet from the nais.yaml file of Saksoversikt refering to the problematic property file:
```
...
  - alias: "saksoversikt.properties"
    resourceType: applicationProperties
...
```
	
Snippet form the saksoversikt.properties file that is defined in Fasit:
```
temasider.viktigavitelenke=DAG,AAP,IND

# Gruppering av sakstema
saksoversikt.temagrupper=ARBEID,FAMILIE
```
The problem is the line starting with #.

**Comment by davidsteinsland** [comment]
a bit on the side, but is this configuration that could be included in the app?

**Comment by Kyrremann** [comment]
I'll fix the issue with comments. Just need to skip lines starting with `#`.

**Comment by davidsteinsland** [comment]
I'm a bit reluctant to add support for comments, because this opens the door for other things as well. 
In my mind, comments in applicationProperties in Fasit is either misplaced or redundant. 

Is `#` the only way to write comments in properties, or should `//` and `/* .. */` also work?

**Comment by Kyrremann** [comment]
I don't see the problem with comments in a large property file, but, we should standardise on one type of comment, and then the one-line style. Like most of the config-files do. I would prefer `#`, but we can add support for both `#` and `//`.

**Comment by Kyrremann** [comment]
About "opening doors for other things", we should handle things case by case, instead of saying no to one thing, because it _can_ lead to something else.

**Comment by davidsteinsland** [comment]
The problem is that adding support for comments encourages the usage of it. applicationProprties in Fasit is often things that could go directly in the app instead, and I think nais should focus on that.

**Comment by Kyrremann** [comment]
I'm not that familiar with `applicationProperties` in Fasit, but as long as we support Fasit, we should also support what Fasit allows. 

But, yeah, if it could just be entered straight into the app, it would be best to move it.

Also, I'm like comments in config files, keeps the documentation close to the source.

**Comment by greger-nl** [comment]
@davidsteinsland yes, we will definitely move more of the properties inside the application. Our first focus is to get the application running on Nais, and then clean up the use of properties.

**Comment by greger-nl** [comment]
Our strategy is to not change to much at the same time, as we have recently inherited the application.

**Comment by jhrv** [comment]
+1 for the regexp solution, would make it more robust

**Comment by davidsteinsland** [comment]
I agree with using regex instead of forcing people to have minimalistic applicationProperties, though a bit reluctantly.. 👍
