### ISSUE TITLE
Environment-vars from Fasit-ApplicationProperties missing prefix

### ISSUE THREAD

**Issue by ctryti** [nais/naisd#120]
When an application uses an ApplicationProperties Fasit-resource, the properties are exposed in the container without the alias-prefix, as it does when deploying with the Aura-plugin (https://confluence.adeo.no/display/AURA/Applikasjonsspesifikke+properties).

Without this prefix, it would be very easy to overwrite existing properties if the properties in the Fasit-resource have generic names, e.g `timeout`, `baseurl`, `port`.

**Comment by jhrv** [comment]
I think this was intended for naisd.
Naming collisions can occur, but it should be fairly easy to prevent as you have full control over the names and also have a mapping functionality (propertyMap) in nais.yaml
