### ISSUE TITLE
Need some way of exposing truststore to nais apps for TLS handshake

### ISSUE THREAD

**Issue by joakibj** [nais/naisd#22]
On the jboss nodes there is readily generated keystore and truststore files exposed to the apps.

Nais needs some mechanism to supply the same readily available for the app containers. The truststore itself and the secret.

Example on jboss standalone.xml:
```
    <system-properties>
        <property name="javax.net.ssl.trustStore" value="/opt/jboss/etc/truststore.jts"/>
        <property name="javax.net.ssl.trustStorePassword" value="${truststorepassword}"/>
        <property name="javax.net.ssl.keyStore" value="/opt/jboss/etc/keystore.jks"/>
        <property name="javax.net.ssl.keyStorePassword" value="${keystorepassword}"/>
    </system-properties>
```
/opt/jboss/etc:

```
lrwxrwxrwx. 1 root         root         32 Aug 29 13:50 keystore.jks -> /etc/pki/tls/private/keystore.ks
lrwxrwxrwx. 1 root         root         32 Aug 29 13:50 truststore.jts -> /etc/pki/tls/certs/truststore.ts
```
(or is this even necessary?)

**Comment by gtcno** [comment]
Related to [this issue](https://github.com/nais/naisd/issues/15) so lets continue the discussion here.

**Comment by jhrv** [comment]
Which certificates do you need?

**Comment by gtcno** [comment]
Regarding Fasit certificates. We will fetch these from Fasit, store them as a K8s secret and mount the certififace and key store password into the container.

**Comment by gtcno** [comment]
Fetch file resources from Fasit where applicable
Add them to application secret
Mount file resources to /var/run/secrets/naisd.io/

**Comment by gtcno** [comment]
To avoid name conflicts files will be mounted based upon fasit aliasKey and file name.
So given
  "type": "certificate",
  "alias": "srvvarseloppgave_cert",
   "files": {
    "keystore": {
      "filename": "keystore",
      "ref": "https://fasit.adeo.no/api/v2/resources/3024713/file/keystore"
    }
The keystore file will be mounted to /var/run/secrets/naisd.io/srvvarseloppgave_cert_keystore

**Comment by gtcno** [comment]
We also only fetch files for resources of type "certificate".
