### ISSUE TITLE
Registering exposed resources

### ISSUE THREAD

**Issue by frodesundby** [nais/naisd#26]
Once an application has been deployed, its exposed resources should be registered on an application instance in Fasit, in order to expose services to applications outside the NAIS eco system.

**Comment by joakibj** [comment]
How goes this? I am starting to get more and more questions if our app is available in environment XX. Since it's not visible in Fasit and Vera. In addition, the service-gw WSRR provisioning no longer happens automagically and needs to be run manually for nais apps.

**Comment by frodesundby** [comment]
This was an interesting one, as there isn't necessarily a direct mapping between a NAIS namespace and a Fasit environment.
Some applications will be quite well suited for the default namespace, whereas some will reside in a namespace dedicated to the team owning the applications - neither of these have a natural environment equivalent in Fasit. Since Fasits data model only allows globally unique environment names (per now), the suggested solution is to map the default namespace in each cluster to a Fasit environment bearing the cluster name. (ie. preprod-fss, prod-fss)
Team specific namespaces will be mapped to an environment named <namespace>-<clustername>.
Applications that fit in the existing environment model, will have a direct mapping between namespace and environment name.

So far we've implemented the necessary changes in Fasit backend to be able to register applicationInstances with the information available in naisd. 
Work on naisd is in progress here: https://github.com/nais/naisd/tree/26-update_fasit

**Comment by joakibj** [comment]
Okay this looks like a good compromise between old and new. Looking forward to try this out. Meanwhile I manually registered some fasit environment namespaces t4,q1,q4 on the preprod-fss cluster to please our consumers.

This also goes in to a broader discussion about how environments should be handled in the future.

**Comment by gtcno** [comment]
Could this be solved by implementing a seperate watcher service, thus reducing the reponsibility of naisd and reducing the NAV specific stuff om naisd?

**Comment by audunstrand** [comment]
that is a great idea. it's a slot a step in the right direction of making smaller components

**Comment by frodesundby** [comment]
We’ve pondered the alternative, but concluded earlier that it made sense to keep the logic in naisd, as naisd already has all the information required and needs to have the information in order to create the resources/variables for the application in nais. 
Adding a component that fetches fasit data before passing it to naisd, which in turn acts on the information, then pass it back to the first component again to update fasit seemed unnecessarily complex. 
I do, however, like the idea of a clean naisd, so I’m up for re-weighing the pros and cons

**Comment by gtcno** [comment]
But the information for creating fasit resources is also added to k8s resources? 
Or if not could be added to an appropriate k8s resource as an annotation.

Calling FASIT should be unnecessary.

**Comment by jhrv** [comment]
@gtcno not atm. We would have to create a separate custom resource for this. 
We still need to call Fasit when registering the deployment itself, as well as when fetching the resource-info (like today). 

One possible solution (a bit down the road) is for naisd to simply emit an event with info about the deployment and have a separate process listening to this and register both the resources and the application instance. This pattern could be done storing the state either in a k8s custom resource or a event/record. 

I think we should do the minimal thing here, and see how we actually end up using Fasit once we get more usage.
