### ISSUE TITLE
Update deployment spec for existing deployments.

### ISSUE THREAD

**Issue by gtcno** [nais/naisd#38]
If a deployment exists we do not update the deployment spec.
This makes it difficult to rollout changes to existing deployments.

**Comment by gtcno** [comment]
I dont see how 679e8a3 fixes this issue. For instance if you need to change progressExceeded or want to set image pull strategy on existing deployment.

**Comment by jhrv** [comment]
I thought the issue was that you were overwriting the resourceversion when replacing the entire objectmeta object.

Can you provide some more information about the issue?

**Comment by gtcno** [comment]
We only write v1beta1.DeploymentSpec for new deployments, thus if you update fields in the v1beta1.DeploymentSpec struct  the changes will never reach existing deployments.

**Comment by jhrv** [comment]
Ah, I understand what you mean now. Fixing.

**Comment by jhrv** [comment]
We were already updating all the fields the user controls, so just to confirm - you mean when/if we change the static defaults set in naisd, these changes are applied to existing deployments?

**Comment by gtcno** [comment]
Yes.
