### ISSUE TITLE
Canary/Partial deployment mechanism

### ISSUE THREAD

**Issue by jhrv** [nais/naisd#5]
Allow for deployment of new version to a configurable percentage/subset of pods 

Rationale:
To lower the barrier of deploying new versions. 
Being able to only affect parts of the traffic and monitor (automatically or manually) can be useful for some deployments, before further increase or full deployment.

**Comment by audunstrand** [comment]
This should be done using istio or something similar. Then traffic routing is done in the mesh layer

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Kyrremann** [comment]
Blir ikke løst i Naisd, kan bli sett på i nais/naiserator eller skya.
