### ISSUE TITLE
Will naisd do WSRR provisioning / promotion as the current aura deploy does?

### ISSUE THREAD

**Issue by joakibj** [nais/naisd#52]
Title.

The current aura deploy provisions SOAP endpoints in WSRR so they are exposed to service-gw.
This needs to be handled by the platform deployment somehow as teams do not have general access to WSRR currently.

**Comment by matsbyfl** [comment]
This is not done by Aura deploy today. WSRR, service-gw etc are separate plugins. These are orchestrated by the "Autodeploy" service ATOM provides. 
ATOM are looking for integrating NAIS deployment in the same deployment service so that developers have one single doplyment endpoint to rule them all

**Comment by joakibj** [comment]
OK awesome, so when we want to deploy to NAIS, it goes through the JIRA ticketing system, triggers "Autodeploy" -> naisd and everyone is happy? Very fine!

As long as we don't have to touch any IBM black magic we'll be happy campers.

**Comment by matsbyfl** [comment]
One does not simply touch IBM stuff :)

**Comment by joakibj** [comment]
I got my answers, looks like you got this covered. Closing.
