### ISSUE TITLE
Jobs support

### ISSUE THREAD

**Issue by davidsteinsland** [nais/naisd#54]
We would like to have a container we could run on a cron schedule or similar to do batch tasks.

https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/

**Comment by audunstrand** [comment]
@gtcno have had contaced with some others that are looking into this. Maybe he can share some knowledge

**Comment by Kyrremann** [comment]
Flyttet til https://github.com/nais/naiserator/issues/25
