### ISSUE TITLE
Warnings when default health check is used

### ISSUE THREAD

**Issue by davidsteinsland** [nais/naisd#57]
I think `naisd` should output some kind of warning during deploy if default health check is used, to help new nais users better understand why their deploys are failing.

If they don't specify health checks in `nais.yaml`, some defaults are used instead. 
But what if they haven't implemented health checks? The deploy will fail because kubernetes will get a `404 not found` when checking the probes. 

To see this error, users will have to use `kubectl describe po <pod>` or similar. This adds a new layer of complexity for new users.

**Comment by jhrv** [comment]
What is the default if nothing is specified?

**Comment by davidsteinsland** [comment]
The defaults seem to be `/isAlive` and `/isReady`:
https://github.com/nais/naisd/blob/master/api/defaults.go#L22-L33

**Comment by jhrv** [comment]
You're right. I wasn't aware that we set this from naisd, I thought you ment kubernetes defaults. 
Maybe we should remove these default values as they can cause some confusion. Only drawback I can see is that if you want to keep the yaml as small as possible you will have to specify this even though you adhere to the default/standard.
@gtcno @frodesundby

**Comment by davidsteinsland** [comment]
If it's possible to detect whether the app has been deployed before, can we output a notice/error during first-time deployment? This way we get to keep the defaults and new users may catch a bug.

**Comment by audunstrand** [comment]
If we remove default we should fail if not at least ifAlive isnset

**Comment by gtcno** [comment]
I think we should output the defaults we are using. 
Readyness, Liveness as well as resource limits and requests as this is confusing for our users when their pods does not become ready.

Maybe we could do a -v flag ?

**Comment by davidsteinsland** [comment]
Or maybe we can detect that the app fails because of liveness/readyness probe issues, and output a warning?
```
[WARNING] Your last deployment failed because readyness check failed. Make sure you have implemented this.
```

**Comment by gtcno** [comment]
On second thought I think it should be enough make Kubernetes events searchable in Kibana. Of course mapping events so specific applications where appropriate. 
I remember we used to have a small application in FINN which used watched k8s events and dumped them to stdout. 
Developers then just did a simple app:myApp search in Kibana  to find out why their application failed to deploy.

This is of course vey handy in many other use cases as well.

**Comment by jhrv** [comment]
It's a huge benefit if we can make it easier for the users to understand why their pods isn't running. Let's definately log these events. 
This might mean that we can keep the yaml and defaults value as simple as they are today, without any special logic for this. Would this make any difference @davidsteinsland ?

**Comment by davidsteinsland** [comment]
yeah, big 👍 for the kibana solution. users should familiarize themselves with kibana anyways, in my opinion

**Comment by gtcno** [comment]
I found this https://github.com/softonic/kubewatch, which write events to stdout. 
Check kibana:

https://<URL-HERE>/app/kibana#/discover?_g=(refreshInterval:(%27$$hashKey%27:%27object:2508%27,display:%2730%20seconds%27,pause:!t,section:1,value:30000),time:(from:now-30m,mode:quick,to:now))&_a=(columns:!(message,environment,level,host),filters:!((%27$state%27:(store:appState),meta:(alias:!n,disabled:!f,index:%27logstash-apps-*%27,key:application,negate:!f,type:phrase,value:kubewatch),query:(match:(application:(query:kubewatch,type:phrase))))),index:%27logstash-apps-*%27,interval:auto,query:(match_all:()),sort:!(%27@timestamp%27,desc))


However I have not found an easy way to find the events for a specific apps.
We need the namespace, application, pod etc of the resource that is involved and not the watcher pod. 
I guess we could do a wild card search on x_involvedObject_name, which is not very user-friendly 
So I am leaning towards writing our own kubewatcher.. 

Any thoughts?

**Comment by gtcno** [comment]
Closing as we are now logging events.
