### ISSUE TITLE
Logformat annotation

### ISSUE THREAD

**Issue by terjesannum** [nais/naisd#61]
Add option in `nais.yaml` to specify the format of the logs from the container if the logs should be handled differently than plain text or json. E.g. if the container outputs NCSA access log, tell this with `logformat: accesslog`

The pod should then get the annotation `nais.io/logformat: accesslog`, and logs will be handled accordingly.

**Comment by Kyrremann** [comment]
Trenger også denne anoteringen `nais.io/logtransform`.
