### ISSUE TITLE
support for container lifecycle hooks in nais.yaml

### ISSUE THREAD

**Issue by dagframstad** [nais/naisd#62]
Make it possible to add lifecycle hooks, like this:
```lifecycle:
      postStart:
        exec:
          command:
            - "touch"
            - "/var/log/lifecycle/post-start"
      preStop:
        httpGet:
          path: "/abort"
          port: 8080

**Comment by gtcno** [comment]
I am thinking:

lifecycle:  //Optional. Defaults to none
  preStop:
    httpGet:
      path: "/stop"

- Lets not get creative by allowing shell execution (exec) when not needed.
- No need for postStart for now.
- No need to specify port as we are only using one default port.
- Extendible to full k8s support if needed.

**Comment by audunstrand** [comment]
man trenger vel bare 

preStop:
   path:"/stop"

siden vi bare godtar http

**Comment by gtcno** [comment]
Yes. At the cost of ease if we were to include support for exec and/or multiple ports in the future.

**Comment by gtcno** [comment]
To keep it as simple as possible:

Added field preStopHookPath to nais.yaml.
