### ISSUE TITLE
Use other readiness/liveness methods then HTTP

### ISSUE THREAD

**Issue by TheUnnamedDude** [nais/naisd#65]
We're currently making a application that doesn't have any HTTP server. Since we don't want to embed a HTTP server just for answering readiness/liveness probes it would be nice if the command feature could be exposed for nais applications.

**Comment by jhrv** [comment]
I agree, we will expose the configuration for this to nais.yaml

**Comment by audunstrand** [comment]
What kind of app I this. You would probably expose an http endpoint for metrics anyway. 

Also exposing an http endpoint is not much work

**Comment by TheUnnamedDude** [comment]
The application that would use this is currently on hold. But its an application that is supposed to deliver messages to Sikker Digital Post. Its planned for it to just pull messages from a Kafka topic, do some transformations and send it to SDP. There would also be an application pulling SDP for receipts and putting them on a Kafka topic. However writing this is stalled for now.

When I initially had a conversation on slack about this I didn't think about having metrics, however it was mentioned later that I could use push gateway to handle metrics. If you think its a better solution to just put up a HTTP server for metrics and readiness/liveness probes I'm fine with that.

**Comment by audunstrand** [comment]
I think an http server is the best. It's five lines of code :)

**Comment by gtcno** [comment]
Easier yes. But I dont think we should force our users to include an http server. We are going to need push gateway for jobs  and it's just a flag in the prometheus chart to enable.

Tcp  and exec checks are well supporterted in Vanilla k8s so why not NAIS?
